from setuptools import setup, find_packages

setup(
    name='mydftlib',
    version='0.1',
    packages=find_packages(),
    description='A DFT workflow Python package',
    author='Nisa Ulumuddin',
    python_requires='>=3.11',
)
